// Compiled shader for Windows, Mac, Linux

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/New Shader Graph" {
Properties {
[HideInInspector]  _BUILTIN_QueueOffset ("Float", Float) = 0.000000
[HideInInspector]  _BUILTIN_QueueControl ("Float", Float) = -1.000000
}
SubShader { 
 Tags { "QUEUE"="Geometry" "RenderType"="Opaque" "ShaderGraphShader"="true" "ShaderGraphTargetId"="BuiltInUnlitSubTarget" "BuiltInMaterialType"="Unlit" }


 // Stats for Vertex shader:
 //        d3d11: 34 math, 2 branch
 Pass {
  Name "Pass"
  Tags { "LIGHTMODE"="FORWARDBASE" "QUEUE"="Geometry" "SHADOWSUPPORT"="true" "RenderType"="Opaque" "ShaderGraphShader"="true" "ShaderGraphTargetId"="BuiltInUnlitSubTarget" "BuiltInMaterialType"="Unlit" }
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: DIRECTIONAL
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0.500000,0.500000,0.500000,1.000000)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: DIRECTIONAL LIGHTPROBE_SH
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0.500000,0.500000,0.500000,1.000000)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: DIRECTIONAL SHADOWS_SCREEN
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0.500000,0.500000,0.500000,1.000000)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0.500000,0.500000,0.500000,1.000000)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: DIRECTIONAL VERTEXLIGHT_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// No shader variant for this keyword set. The closest match will be used instead.

//////////////////////////////////////////////////////
Keywords: DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// No shader variant for this keyword set. The closest match will be used instead.

//////////////////////////////////////////////////////
Keywords: DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// No shader variant for this keyword set. The closest match will be used instead.

//////////////////////////////////////////////////////
Keywords: DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// No shader variant for this keyword set. The closest match will be used instead.

 }


 // Stats for Vertex shader:
 //        d3d11: 34 math, 2 branch
 Pass {
  Name "DepthOnly"
  Tags { "LIGHTMODE"="DepthOnly" "QUEUE"="Geometry" "RenderType"="Opaque" "ShaderGraphShader"="true" "ShaderGraphTargetId"="BuiltInUnlitSubTarget" "BuiltInMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 34 math, 5 temp registers, 2 branches
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityPerDraw" (176 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float       
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyz, r0.yyyy, cb0[1].xyzx
  42: mad r0.xyw, cb0[0].xyxz, r0.xxxx, r1.xyxz
  43: mad r0.xyz, cb0[2].xyzx, r0.zzzz, r0.xywx
  44: add r0.xyz, r0.xyzx, cb0[3].xyzx
  45: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
  46: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
  47: mad r0.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
  48: add o0.xyzw, r0.xyzw, cb1[20].xyzw
  49: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }


 // Stats for Vertex shader:
 //        d3d11: 55 avg math (53..57), 2 branch
 Pass {
  Name "ShadowCaster"
  Tags { "LIGHTMODE"="SHADOWCASTER" "QUEUE"="Geometry" "SHADOWSUPPORT"="true" "RenderType"="Opaque" "ShaderGraphShader"="true" "ShaderGraphTargetId"="BuiltInUnlitSubTarget" "BuiltInMaterialType"="Unlit" }
  ColorMask 0
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Keywords: SHADOWS_DEPTH
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 57 math, 5 temp registers, 2 branches
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v1.xyz
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
  42: mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
  43: mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
  44: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  45: ne r1.x, cb1[5].z, l(0.000000)
  46: dp3 r2.x, v1.xyzx, cb2[4].xyzx
  47: dp3 r2.y, v1.xyzx, cb2[5].xyzx
  48: dp3 r2.z, v1.xyzx, cb2[6].xyzx
  49: dp3 r1.y, r2.xyzx, r2.xyzx
  50: rsq r1.y, r1.y
  51: mul r1.yzw, r1.yyyy, r2.xxyz
  52: mad r2.xyz, -r0.xyzx, cb0[0].wwww, cb0[0].xyzx
  53: dp3 r2.w, r2.xyzx, r2.xyzx
  54: rsq r2.w, r2.w
  55: mul r2.xyz, r2.wwww, r2.xyzx
  56: dp3 r2.x, r1.yzwy, r2.xyzx
  57: mad r2.x, -r2.x, r2.x, l(1.000000)
  58: sqrt r2.x, r2.x
  59: mul r2.x, r2.x, cb1[5].z
  60: mad r1.yzw, -r1.yyzw, r2.xxxx, r0.xxyz
  61: movc r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  62: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  63: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  64: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  65: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  66: div r1.x, cb1[5].x, r0.w
  67: min r1.x, r1.x, l(0.000000)
  68: max r1.x, r1.x, l(-1.000000)
  69: add r0.z, r0.z, r1.x
  70: min r1.x, r0.w, r0.z
  71: add r1.x, -r0.z, r1.x
  72: mad o0.z, cb1[5].y, r1.x, r0.z
  73: mov o0.xyw, r0.xyxw
  74: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SHADOWS_CUBE
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 53 math, 5 temp registers, 2 branches
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v1.xyz
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
  42: mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
  43: mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
  44: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  45: ne r1.x, cb1[5].z, l(0.000000)
  46: dp3 r2.x, v1.xyzx, cb2[4].xyzx
  47: dp3 r2.y, v1.xyzx, cb2[5].xyzx
  48: dp3 r2.z, v1.xyzx, cb2[6].xyzx
  49: dp3 r1.y, r2.xyzx, r2.xyzx
  50: rsq r1.y, r1.y
  51: mul r1.yzw, r1.yyyy, r2.xxyz
  52: mad r2.xyz, -r0.xyzx, cb0[0].wwww, cb0[0].xyzx
  53: dp3 r2.w, r2.xyzx, r2.xyzx
  54: rsq r2.w, r2.w
  55: mul r2.xyz, r2.wwww, r2.xyzx
  56: dp3 r2.x, r1.yzwy, r2.xyzx
  57: mad r2.x, -r2.x, r2.x, l(1.000000)
  58: sqrt r2.x, r2.x
  59: mul r2.x, r2.x, cb1[5].z
  60: mad r1.yzw, -r1.yyzw, r2.xxxx, r0.xxyz
  61: movc r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  62: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  63: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  64: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  65: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  66: min r1.x, r0.w, r0.z
  67: add r1.x, -r0.z, r1.x
  68: mad o0.z, cb1[5].y, r1.x, r0.z
  69: mov o0.xyw, r0.xyxw
  70: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SHADOWS_DEPTH _CASTING_PUNCTUAL_LIGHT_SHADOW
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 57 math, 5 temp registers, 2 branches
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v1.xyz
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
  42: mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
  43: mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
  44: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  45: ne r1.x, cb1[5].z, l(0.000000)
  46: dp3 r2.x, v1.xyzx, cb2[4].xyzx
  47: dp3 r2.y, v1.xyzx, cb2[5].xyzx
  48: dp3 r2.z, v1.xyzx, cb2[6].xyzx
  49: dp3 r1.y, r2.xyzx, r2.xyzx
  50: rsq r1.y, r1.y
  51: mul r1.yzw, r1.yyyy, r2.xxyz
  52: mad r2.xyz, -r0.xyzx, cb0[0].wwww, cb0[0].xyzx
  53: dp3 r2.w, r2.xyzx, r2.xyzx
  54: rsq r2.w, r2.w
  55: mul r2.xyz, r2.wwww, r2.xyzx
  56: dp3 r2.x, r1.yzwy, r2.xyzx
  57: mad r2.x, -r2.x, r2.x, l(1.000000)
  58: sqrt r2.x, r2.x
  59: mul r2.x, r2.x, cb1[5].z
  60: mad r1.yzw, -r1.yyzw, r2.xxxx, r0.xxyz
  61: movc r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  62: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  63: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  64: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  65: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  66: div r1.x, cb1[5].x, r0.w
  67: min r1.x, r1.x, l(0.000000)
  68: max r1.x, r1.x, l(-1.000000)
  69: add r0.z, r0.z, r1.x
  70: min r1.x, r0.w, r0.z
  71: add r1.x, -r0.z, r1.x
  72: mad o0.z, cb1[5].y, r1.x, r0.z
  73: mov o0.xyw, r0.xyxw
  74: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


//////////////////////////////////////////////////////
Keywords: SHADOWS_CUBE _CASTING_PUNCTUAL_LIGHT_SHADOW
-- Hardware tier variant: Tier 1
-- Vertex shader for "d3d11":
// Stats: 53 math, 5 temp registers, 2 branches
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord2"

Constant Buffer "UnityLighting" (768 bytes) on slot 0 {
  Vector4 _WorldSpaceLightPos0 at 0
}
Constant Buffer "UnityShadows" (416 bytes) on slot 1 {
  Vector4 unity_LightShadowBias at 80
}
Constant Buffer "UnityPerDraw" (176 bytes) on slot 2 {
  Matrix4x4 unity_ObjectToWorld at 0
  Matrix4x4 unity_WorldToObject at 64
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 3 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float       
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float       
// TEXCOORD                 2   xyzw        3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[1], immediateIndexed
      dcl_constantbuffer CB1[6], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_input v1.xyz
      dcl_input v3.xy
      dcl_output_siv o0.xyzw, position
      dcl_temps 5
   0: mul r0.xy, v3.xyxx, l(5.000000, 5.000000, 0.000000, 0.000000)
   1: round_ni r0.zw, r0.xxxy
   2: frc r0.xy, r0.xyxx
   3: mov r1.xyz, l(0,8.000000,-1,0)
   4: loop 
   5:   ilt r1.w, l(1), r1.z
   6:   breakc_nz r1.w
   7:   itof r2.y, r1.z
   8:   mov r2.zw, r1.xxxy
   9:   mov r1.w, l(-1)
  10:   loop 
  11:     ilt r3.x, l(1), r1.w
  12:     breakc_nz r3.x
  13:     itof r2.x, r1.w
  14:     add r3.xy, r0.zwzz, r2.xyxx
  15:     ftoi r3.xy, r3.xyxx
  16:     xor r3.y, r3.y, l(0x41c64e6d)
  17:     iadd r3.x, r3.y, r3.x
  18:     imul null, r3.x, r3.y, r3.x
  19:     ushr r3.z, r3.x, l(5)
  20:     xor r3.x, r3.z, r3.x
  21:     imul null, r3.x, r3.x, l(0x27d4eb2d)
  22:     ishl r3.z, r3.x, l(3)
  23:     xor r3.y, r3.z, r3.y
  24:     utof r4.xy, r3.yxyy
  25:     mul r3.xy, r4.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  26:     sincos r4.x, null, r3.x
  27:     sincos null, r4.y, r3.y
  28:     mad r3.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.xyxx
  29:     add r3.xy, -r0.xyxx, r3.xyxx
  30:     add r3.xy, r3.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  31:     dp2 r2.x, r3.xyxx, r3.xyxx
  32:     sqrt r2.x, r2.x
  33:     lt r3.x, r2.x, r2.w
  34:     movc r2.zw, r3.xxxx, r2.xxxx, r2.zzzw
  35:     iadd r1.w, r1.w, l(1)
  36:   endloop 
  37:   mov r1.xy, r2.zwzz
  38:   iadd r1.z, r1.z, l(1)
  39: endloop 
  40: mul r0.xyz, r1.xxxx, l(0.858491, 0.677572, 0.359594, 0.000000)
  41: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
  42: mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
  43: mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
  44: add r0.xyzw, r0.xyzw, cb2[3].xyzw
  45: ne r1.x, cb1[5].z, l(0.000000)
  46: dp3 r2.x, v1.xyzx, cb2[4].xyzx
  47: dp3 r2.y, v1.xyzx, cb2[5].xyzx
  48: dp3 r2.z, v1.xyzx, cb2[6].xyzx
  49: dp3 r1.y, r2.xyzx, r2.xyzx
  50: rsq r1.y, r1.y
  51: mul r1.yzw, r1.yyyy, r2.xxyz
  52: mad r2.xyz, -r0.xyzx, cb0[0].wwww, cb0[0].xyzx
  53: dp3 r2.w, r2.xyzx, r2.xyzx
  54: rsq r2.w, r2.w
  55: mul r2.xyz, r2.wwww, r2.xyzx
  56: dp3 r2.x, r1.yzwy, r2.xyzx
  57: mad r2.x, -r2.x, r2.x, l(1.000000)
  58: sqrt r2.x, r2.x
  59: mul r2.x, r2.x, cb1[5].z
  60: mad r1.yzw, -r1.yyzw, r2.xxxx, r0.xxyz
  61: movc r0.xyz, r1.xxxx, r1.yzwy, r0.xyzx
  62: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
  63: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
  64: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
  65: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
  66: min r1.x, r0.w, r0.z
  67: add r1.x, -r0.z, r1.x
  68: mad o0.z, cb1[5].y, r1.x, r0.z
  69: mov o0.xyw, r0.xyxw
  70: ret 
// Approximately 0 instruction slots used


-- Hardware tier variant: Tier 1
-- Fragment shader for "d3d11":
Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_output o0.xyzw
   0: mov o0.xyzw, l(0,0,0,0)
   1: ret 
// Approximately 0 instruction slots used


 }
}
CustomEditor "UnityEditor.ShaderGraph.GenericShaderGraphMaterialGUI"
Fallback "Hidden/Shader Graph/FallbackError"
}